title: Surviving DACS
description: A survival guide to the Department of Advanced Computing Sciences at Maastricht University
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme

gems:
  - jekyll-mentions
