title: Surviving DACS
description: A survival guide to the Department of Advanced Computing Sciences at Maastricht University
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
